---
title: NYC Graffiti Tour
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
incremental: true
tagline: NYC’s most immersive graffiti tour.
description: NYC’s most immersive graffiti tour. Spend a night with a real NYC graffiti
  artist, painting real graffiti.
